package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/data/data-goes-here.txt", "assets/data/data-goes-here.txt");
			type.set ("assets/data/data-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/music/HaxeFlixel_Tutorial_Game.mp3", "assets/music/HaxeFlixel_Tutorial_Game.mp3");
			type.set ("assets/music/HaxeFlixel_Tutorial_Game.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/music/run.ogg", "assets/music/run.ogg");
			type.set ("assets/music/run.ogg", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/music/music-goes-here.txt", "assets/music/music-goes-here.txt");
			type.set ("assets/music/music-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/music/run.mp3", "assets/music/run.mp3");
			type.set ("assets/music/run.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/crumble.wav", "assets/sounds/crumble.wav");
			type.set ("assets/sounds/crumble.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/lose.wav", "assets/sounds/lose.wav");
			type.set ("assets/sounds/lose.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/hurt.wav", "assets/sounds/hurt.wav");
			type.set ("assets/sounds/hurt.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/bomb_explode.mp3", "assets/sounds/bomb_explode.mp3");
			type.set ("assets/sounds/bomb_explode.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/bomb_launch.mp3", "assets/sounds/bomb_launch.mp3");
			type.set ("assets/sounds/bomb_launch.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/bomb_hit.mp3", "assets/sounds/bomb_hit.mp3");
			type.set ("assets/sounds/bomb_hit.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/giant_leg.mp3", "assets/sounds/giant_leg.mp3");
			type.set ("assets/sounds/giant_leg.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/obstacle1.mp3", "assets/sounds/obstacle1.mp3");
			type.set ("assets/sounds/obstacle1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/footc3.mp3", "assets/sounds/footc3.mp3");
			type.set ("assets/sounds/footc3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/footc2.mp3", "assets/sounds/footc2.mp3");
			type.set ("assets/sounds/footc2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/bomb_pre.mp3", "assets/sounds/bomb_pre.mp3");
			type.set ("assets/sounds/bomb_pre.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/wall.mp3", "assets/sounds/wall.mp3");
			type.set ("assets/sounds/wall.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/step.wav", "assets/sounds/step.wav");
			type.set ("assets/sounds/step.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/window1.mp3", "assets/sounds/window1.mp3");
			type.set ("assets/sounds/window1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/glass1.mp3", "assets/sounds/glass1.mp3");
			type.set ("assets/sounds/glass1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/flyby.mp3", "assets/sounds/flyby.mp3");
			type.set ("assets/sounds/flyby.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/foot2.wav", "assets/sounds/foot2.wav");
			type.set ("assets/sounds/foot2.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/obstacle3.mp3", "assets/sounds/obstacle3.mp3");
			type.set ("assets/sounds/obstacle3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/crumble.mp3", "assets/sounds/crumble.mp3");
			type.set ("assets/sounds/crumble.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/foot2.mp3", "assets/sounds/foot2.mp3");
			type.set ("assets/sounds/foot2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/coin.wav", "assets/sounds/coin.wav");
			type.set ("assets/sounds/coin.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/jump1.mp3", "assets/sounds/jump1.mp3");
			type.set ("assets/sounds/jump1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/foot1.mp3", "assets/sounds/foot1.mp3");
			type.set ("assets/sounds/foot1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/footc1.mp3", "assets/sounds/footc1.mp3");
			type.set ("assets/sounds/footc1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/foot4.mp3", "assets/sounds/foot4.mp3");
			type.set ("assets/sounds/foot4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/giant_leg_release.mp3", "assets/sounds/giant_leg_release.mp3");
			type.set ("assets/sounds/giant_leg_release.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/foot3.mp3", "assets/sounds/foot3.mp3");
			type.set ("assets/sounds/foot3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/select.wav", "assets/sounds/select.wav");
			type.set ("assets/sounds/select.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/flap2.mp3", "assets/sounds/flap2.mp3");
			type.set ("assets/sounds/flap2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/obstacle2.mp3", "assets/sounds/obstacle2.mp3");
			type.set ("assets/sounds/obstacle2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/window2.mp3", "assets/sounds/window2.mp3");
			type.set ("assets/sounds/window2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/foot3.wav", "assets/sounds/foot3.wav");
			type.set ("assets/sounds/foot3.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sounds-go-here.txt", "assets/sounds/sounds-go-here.txt");
			type.set ("assets/sounds/sounds-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/tumble.mp3", "assets/sounds/tumble.mp3");
			type.set ("assets/sounds/tumble.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/footc4.mp3", "assets/sounds/footc4.mp3");
			type.set ("assets/sounds/footc4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/miss.wav", "assets/sounds/miss.wav");
			type.set ("assets/sounds/miss.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/foot1.wav", "assets/sounds/foot1.wav");
			type.set ("assets/sounds/foot1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/fled.wav", "assets/sounds/fled.wav");
			type.set ("assets/sounds/fled.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/flap3.mp3", "assets/sounds/flap3.mp3");
			type.set ("assets/sounds/flap3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/flap1.mp3", "assets/sounds/flap1.mp3");
			type.set ("assets/sounds/flap1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/foot4.wav", "assets/sounds/foot4.wav");
			type.set ("assets/sounds/foot4.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/jump3.mp3", "assets/sounds/jump3.mp3");
			type.set ("assets/sounds/jump3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/win.wav", "assets/sounds/win.wav");
			type.set ("assets/sounds/win.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/glass2.mp3", "assets/sounds/glass2.mp3");
			type.set ("assets/sounds/glass2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/jump2.mp3", "assets/sounds/jump2.mp3");
			type.set ("assets/sounds/jump2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/combat.wav", "assets/sounds/combat.wav");
			type.set ("assets/sounds/combat.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/jump1.wav", "assets/sounds/jump1.wav");
			type.set ("assets/sounds/jump1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/images/midground1-trimmed.png", "assets/images/midground1-trimmed.png");
			type.set ("assets/images/midground1-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/background.png", "assets/images/background.png");
			type.set ("assets/images/background.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/floor2-middle.png", "assets/images/floor2-middle.png");
			type.set ("assets/images/floor2-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof5-right-cracked.png", "assets/images/roof5-right-cracked.png");
			type.set ("assets/images/roof5-right-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/crane2-filled.png", "assets/images/crane2-filled.png");
			type.set ("assets/images/crane2-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/giant_leg_top.png", "assets/images/giant_leg_top.png");
			type.set ("assets/images/giant_leg_top.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall3-right-cracked.png", "assets/images/wall3-right-cracked.png");
			type.set ("assets/images/wall3-right-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_bottom-right.png", "assets/images/billboard_bottom-right.png");
			type.set ("assets/images/billboard_bottom-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/floor1-middle.png", "assets/images/floor1-middle.png");
			type.set ("assets/images/floor1-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall2-right.png", "assets/images/wall2-right.png");
			type.set ("assets/images/wall2-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof6-right.png", "assets/images/roof6-right.png");
			type.set ("assets/images/roof6-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/crane5-filled.png", "assets/images/crane5-filled.png");
			type.set ("assets/images/crane5-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/window2_sheet.png", "assets/images/window2_sheet.png");
			type.set ("assets/images/window2_sheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_dmg3-filled.png", "assets/images/billboard_dmg3-filled.png");
			type.set ("assets/images/billboard_dmg3-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_dmg2-filled.png", "assets/images/billboard_dmg2-filled.png");
			type.set ("assets/images/billboard_dmg2-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna4.png", "assets/images/antenna4.png");
			type.set ("assets/images/antenna4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hall2.png", "assets/images/hall2.png");
			type.set ("assets/images/hall2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_dmg3.png", "assets/images/billboard_dmg3.png");
			type.set ("assets/images/billboard_dmg3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_dmg1.png", "assets/images/billboard_dmg1.png");
			type.set ("assets/images/billboard_dmg1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pause-button.png", "assets/images/pause-button.png");
			type.set ("assets/images/pause-button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pipe1-left.png", "assets/images/pipe1-left.png");
			type.set ("assets/images/pipe1-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/fence-trimmed.png", "assets/images/fence-trimmed.png");
			type.set ("assets/images/fence-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof4.png", "assets/images/roof4.png");
			type.set ("assets/images/roof4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof3-middle-cracked.png", "assets/images/roof3-middle-cracked.png");
			type.set ("assets/images/roof3-middle-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall1-right-cracked.png", "assets/images/wall1-right-cracked.png");
			type.set ("assets/images/wall1-right-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall4-middle-cracked.png", "assets/images/wall4-middle-cracked.png");
			type.set ("assets/images/wall4-middle-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/reservoir-trimmed.png", "assets/images/reservoir-trimmed.png");
			type.set ("assets/images/reservoir-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_middle.png", "assets/images/billboard_middle.png");
			type.set ("assets/images/billboard_middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/girder-tall.png", "assets/images/girder-tall.png");
			type.set ("assets/images/girder-tall.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/panel_facebook.png", "assets/images/panel_facebook.png");
			type.set ("assets/images/panel_facebook.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/escape.png", "assets/images/escape.png");
			type.set ("assets/images/escape.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/obstacles.png", "assets/images/obstacles.png");
			type.set ("assets/images/obstacles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/dark_tower.png", "assets/images/dark_tower.png");
			type.set ("assets/images/dark_tower.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall4-right.png", "assets/images/wall4-right.png");
			type.set ("assets/images/wall4-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof3-left.png", "assets/images/roof3-left.png");
			type.set ("assets/images/roof3-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/window1.png", "assets/images/window1.png");
			type.set ("assets/images/window1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/cracks.png", "assets/images/cracks.png");
			type.set ("assets/images/cracks.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/crane4-filled.png", "assets/images/crane4-filled.png");
			type.set ("assets/images/crane4-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof5-left-cracked.png", "assets/images/roof5-left-cracked.png");
			type.set ("assets/images/roof5-left-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/slope20.png", "assets/images/slope20.png");
			type.set ("assets/images/slope20.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna6.png", "assets/images/antenna6.png");
			type.set ("assets/images/antenna6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/access.png", "assets/images/access.png");
			type.set ("assets/images/access.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof2-middle-cracked.png", "assets/images/roof2-middle-cracked.png");
			type.set ("assets/images/roof2-middle-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof5-left.png", "assets/images/roof5-left.png");
			type.set ("assets/images/roof5-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna-left.png", "assets/images/antenna-left.png");
			type.set ("assets/images/antenna-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ac.png", "assets/images/ac.png");
			type.set ("assets/images/ac.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ac-trimmed.png", "assets/images/ac-trimmed.png");
			type.set ("assets/images/ac-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof6-left.png", "assets/images/roof6-left.png");
			type.set ("assets/images/roof6-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/slope.png", "assets/images/slope.png");
			type.set ("assets/images/slope.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_post2.png", "assets/images/billboard_post2.png");
			type.set ("assets/images/billboard_post2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall2-left-cracked.png", "assets/images/wall2-left-cracked.png");
			type.set ("assets/images/wall2-left-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof4-middle.png", "assets/images/roof4-middle.png");
			type.set ("assets/images/roof4-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna-trimmed-second.png", "assets/images/antenna-trimmed-second.png");
			type.set ("assets/images/antenna-trimmed-second.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof1-left-cracked.png", "assets/images/roof1-left-cracked.png");
			type.set ("assets/images/roof1-left-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/gameover_exit_off.png", "assets/images/gameover_exit_off.png");
			type.set ("assets/images/gameover_exit_off.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_middle-right.png", "assets/images/billboard_middle-right.png");
			type.set ("assets/images/billboard_middle-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall2-right-cracked.png", "assets/images/wall2-right-cracked.png");
			type.set ("assets/images/wall2-right-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_dmg2.png", "assets/images/billboard_dmg2.png");
			type.set ("assets/images/billboard_dmg2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof6-middle.png", "assets/images/roof6-middle.png");
			type.set ("assets/images/roof6-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_catwalk.png", "assets/images/billboard_catwalk.png");
			type.set ("assets/images/billboard_catwalk.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/doors.png", "assets/images/doors.png");
			type.set ("assets/images/doors.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof1-right-cracked.png", "assets/images/roof1-right-cracked.png");
			type.set ("assets/images/roof1-right-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof1-middle-cracked.png", "assets/images/roof1-middle-cracked.png");
			type.set ("assets/images/roof1-middle-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof2-left-cracked.png", "assets/images/roof2-left-cracked.png");
			type.set ("assets/images/roof2-left-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/fence.png", "assets/images/fence.png");
			type.set ("assets/images/fence.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pipe2-right.png", "assets/images/pipe2-right.png");
			type.set ("assets/images/pipe2-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/jet.png", "assets/images/jet.png");
			type.set ("assets/images/jet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/bar.png", "assets/images/bar.png");
			type.set ("assets/images/bar.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof5-middle.png", "assets/images/roof5-middle.png");
			type.set ("assets/images/roof5-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof3.png", "assets/images/roof3.png");
			type.set ("assets/images/roof3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall1.png", "assets/images/wall1.png");
			type.set ("assets/images/wall1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall2-middle-cracked.png", "assets/images/wall2-middle-cracked.png");
			type.set ("assets/images/wall2-middle-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna2.png", "assets/images/antenna2.png");
			type.set ("assets/images/antenna2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/dishes-trimmed.png", "assets/images/dishes-trimmed.png");
			type.set ("assets/images/dishes-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof6-left-cracked.png", "assets/images/roof6-left-cracked.png");
			type.set ("assets/images/roof6-left-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof3-right.png", "assets/images/roof3-right.png");
			type.set ("assets/images/roof3-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_top-middle.png", "assets/images/billboard_top-middle.png");
			type.set ("assets/images/billboard_top-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/player.png", "assets/images/player.png");
			type.set ("assets/images/player.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/paused-reverse.png", "assets/images/paused-reverse.png");
			type.set ("assets/images/paused-reverse.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pipe1.png", "assets/images/pipe1.png");
			type.set ("assets/images/pipe1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/block.png", "assets/images/block.png");
			type.set ("assets/images/block.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof1-left.png", "assets/images/roof1-left.png");
			type.set ("assets/images/roof1-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/midground1.png", "assets/images/midground1.png");
			type.set ("assets/images/midground1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall1-right.png", "assets/images/wall1-right.png");
			type.set ("assets/images/wall1-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna5.png", "assets/images/antenna5.png");
			type.set ("assets/images/antenna5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof3-middle.png", "assets/images/roof3-middle.png");
			type.set ("assets/images/roof3-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/giant_leg_bottom.png", "assets/images/giant_leg_bottom.png");
			type.set ("assets/images/giant_leg_bottom.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof1.png", "assets/images/roof1.png");
			type.set ("assets/images/roof1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/cursor.png", "assets/images/cursor.png");
			type.set ("assets/images/cursor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/walker.png", "assets/images/walker.png");
			type.set ("assets/images/walker.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/escape-trimmed-filled.png", "assets/images/escape-trimmed-filled.png");
			type.set ("assets/images/escape-trimmed-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/crane1.png", "assets/images/crane1.png");
			type.set ("assets/images/crane1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/floor2-right.png", "assets/images/floor2-right.png");
			type.set ("assets/images/floor2-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/reservoir.png", "assets/images/reservoir.png");
			type.set ("assets/images/reservoir.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_catwalk-middle.png", "assets/images/billboard_catwalk-middle.png");
			type.set ("assets/images/billboard_catwalk-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof3-left-cracked.png", "assets/images/roof3-left-cracked.png");
			type.set ("assets/images/roof3-left-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pipe2-middle.png", "assets/images/pipe2-middle.png");
			type.set ("assets/images/pipe2-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna5-trimmed.png", "assets/images/antenna5-trimmed.png");
			type.set ("assets/images/antenna5-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall1-left-cracked.png", "assets/images/wall1-left-cracked.png");
			type.set ("assets/images/wall1-left-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/window3.png", "assets/images/window3.png");
			type.set ("assets/images/window3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna.png", "assets/images/antenna.png");
			type.set ("assets/images/antenna.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall4-left-cracked.png", "assets/images/wall4-left-cracked.png");
			type.set ("assets/images/wall4-left-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/gameover_new_record_a.png", "assets/images/gameover_new_record_a.png");
			type.set ("assets/images/gameover_new_record_a.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/block20.png", "assets/images/block20.png");
			type.set ("assets/images/block20.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof4-right.png", "assets/images/roof4-right.png");
			type.set ("assets/images/roof4-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_catwalk-right.png", "assets/images/billboard_catwalk-right.png");
			type.set ("assets/images/billboard_catwalk-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_top-right.png", "assets/images/billboard_top-right.png");
			type.set ("assets/images/billboard_top-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_dmg1-filled.png", "assets/images/billboard_dmg1-filled.png");
			type.set ("assets/images/billboard_dmg1-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/window1_sheet.png", "assets/images/window1_sheet.png");
			type.set ("assets/images/window1_sheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/title.png", "assets/images/title.png");
			type.set ("assets/images/title.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/crane5.png", "assets/images/crane5.png");
			type.set ("assets/images/crane5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/title2.png", "assets/images/title2.png");
			type.set ("assets/images/title2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof2.png", "assets/images/roof2.png");
			type.set ("assets/images/roof2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof4-left-cracked.png", "assets/images/roof4-left-cracked.png");
			type.set ("assets/images/roof4-left-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof5-middle-cracked.png", "assets/images/roof5-middle-cracked.png");
			type.set ("assets/images/roof5-middle-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof6-middle-cracked.png", "assets/images/roof6-middle-cracked.png");
			type.set ("assets/images/roof6-middle-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall3-left.png", "assets/images/wall3-left.png");
			type.set ("assets/images/wall3-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/dove.png", "assets/images/dove.png");
			type.set ("assets/images/dove.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/store_512x512.jpg", "assets/images/store_512x512.jpg");
			type.set ("assets/images/store_512x512.jpg", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/crane4.png", "assets/images/crane4.png");
			type.set ("assets/images/crane4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna3.png", "assets/images/antenna3.png");
			type.set ("assets/images/antenna3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna-trimmed-first.png", "assets/images/antenna-trimmed-first.png");
			type.set ("assets/images/antenna-trimmed-first.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof4-left.png", "assets/images/roof4-left.png");
			type.set ("assets/images/roof4-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/demo_gibs.png", "assets/images/demo_gibs.png");
			type.set ("assets/images/demo_gibs.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall4-left.png", "assets/images/wall4-left.png");
			type.set ("assets/images/wall4-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/midground2.png", "assets/images/midground2.png");
			type.set ("assets/images/midground2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/girder2.png", "assets/images/girder2.png");
			type.set ("assets/images/girder2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/crane3.png", "assets/images/crane3.png");
			type.set ("assets/images/crane3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/paused.png", "assets/images/paused.png");
			type.set ("assets/images/paused.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna-right.png", "assets/images/antenna-right.png");
			type.set ("assets/images/antenna-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_bottom-middle.png", "assets/images/billboard_bottom-middle.png");
			type.set ("assets/images/billboard_bottom-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/midground2-trimmed.png", "assets/images/midground2-trimmed.png");
			type.set ("assets/images/midground2-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall3-right.png", "assets/images/wall3-right.png");
			type.set ("assets/images/wall3-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/gameover_new_record_b.png", "assets/images/gameover_new_record_b.png");
			type.set ("assets/images/gameover_new_record_b.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/crane1-filled.png", "assets/images/crane1-filled.png");
			type.set ("assets/images/crane1-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof6.png", "assets/images/roof6.png");
			type.set ("assets/images/roof6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof6-right-cracked.png", "assets/images/roof6-right-cracked.png");
			type.set ("assets/images/roof6-right-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall3.png", "assets/images/wall3.png");
			type.set ("assets/images/wall3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/floor2.png", "assets/images/floor2.png");
			type.set ("assets/images/floor2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall3-middle.png", "assets/images/wall3-middle.png");
			type.set ("assets/images/wall3-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof2-left.png", "assets/images/roof2-left.png");
			type.set ("assets/images/roof2-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna2-trimmed.png", "assets/images/antenna2-trimmed.png");
			type.set ("assets/images/antenna2-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/glass.png", "assets/images/glass.png");
			type.set ("assets/images/glass.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof5-right.png", "assets/images/roof5-right.png");
			type.set ("assets/images/roof5-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/joinPlists", "assets/images/joinPlists");
			type.set ("assets/images/joinPlists", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/floor1.png", "assets/images/floor1.png");
			type.set ("assets/images/floor1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/images-go-here.txt", "assets/images/images-go-here.txt");
			type.set ("assets/images/images-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/roof2-middle.png", "assets/images/roof2-middle.png");
			type.set ("assets/images/roof2-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/mothership-filled.png", "assets/images/mothership-filled.png");
			type.set ("assets/images/mothership-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/crane2.png", "assets/images/crane2.png");
			type.set ("assets/images/crane2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/paused-highlight.png", "assets/images/paused-highlight.png");
			type.set ("assets/images/paused-highlight.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ipad/midground1-trimmed.png", "assets/images/ipad/midground1-trimmed.png");
			type.set ("assets/images/ipad/midground1-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ipad/background.png", "assets/images/ipad/background.png");
			type.set ("assets/images/ipad/background.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ipad/bar.png", "assets/images/ipad/bar.png");
			type.set ("assets/images/ipad/bar.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ipad/midground1.png", "assets/images/ipad/midground1.png");
			type.set ("assets/images/ipad/midground1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ipad/title.png", "assets/images/ipad/title.png");
			type.set ("assets/images/ipad/title.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ipad/midground2.png", "assets/images/ipad/midground2.png");
			type.set ("assets/images/ipad/midground2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ipad/midground2-trimmed.png", "assets/images/ipad/midground2-trimmed.png");
			type.set ("assets/images/ipad/midground2-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ipad/background-trimmed.png", "assets/images/ipad/background-trimmed.png");
			type.set ("assets/images/ipad/background-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/makeTextureAtlas.sh", "assets/images/makeTextureAtlas.sh");
			type.set ("assets/images/makeTextureAtlas.sh", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/wall2-left.png", "assets/images/wall2-left.png");
			type.set ("assets/images/wall2-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/window4.png", "assets/images/window4.png");
			type.set ("assets/images/window4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/window2.png", "assets/images/window2.png");
			type.set ("assets/images/window2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_middle-middle.png", "assets/images/billboard_middle-middle.png");
			type.set ("assets/images/billboard_middle-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall4-right-cracked.png", "assets/images/wall4-right-cracked.png");
			type.set ("assets/images/wall4-right-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/textureAtlas", "assets/images/textureAtlas");
			type.set ("assets/images/textureAtlas", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/wall2.png", "assets/images/wall2.png");
			type.set ("assets/images/wall2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall1-middle-cracked.png", "assets/images/wall1-middle-cracked.png");
			type.set ("assets/images/wall1-middle-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall4.png", "assets/images/wall4.png");
			type.set ("assets/images/wall4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/mothership.png", "assets/images/mothership.png");
			type.set ("assets/images/mothership.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_bottom.png", "assets/images/billboard_bottom.png");
			type.set ("assets/images/billboard_bottom.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna4-trimmed.png", "assets/images/antenna4-trimmed.png");
			type.set ("assets/images/antenna4-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/dark_tower-filled.png", "assets/images/dark_tower-filled.png");
			type.set ("assets/images/dark_tower-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/girder.png", "assets/images/girder.png");
			type.set ("assets/images/girder.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_bottom-left.png", "assets/images/billboard_bottom-left.png");
			type.set ("assets/images/billboard_bottom-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/floor1-left.png", "assets/images/floor1-left.png");
			type.set ("assets/images/floor1-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/floor2-left.png", "assets/images/floor2-left.png");
			type.set ("assets/images/floor2-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof2-right-cracked.png", "assets/images/roof2-right-cracked.png");
			type.set ("assets/images/roof2-right-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pipe2-left.png", "assets/images/pipe2-left.png");
			type.set ("assets/images/pipe2-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall3-middle-cracked.png", "assets/images/wall3-middle-cracked.png");
			type.set ("assets/images/wall3-middle-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/bomb.png", "assets/images/bomb.png");
			type.set ("assets/images/bomb.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_top-left.png", "assets/images/billboard_top-left.png");
			type.set ("assets/images/billboard_top-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pause.png", "assets/images/pause.png");
			type.set ("assets/images/pause.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/gameover_exit_on.png", "assets/images/gameover_exit_on.png");
			type.set ("assets/images/gameover_exit_on.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall4-middle.png", "assets/images/wall4-middle.png");
			type.set ("assets/images/wall4-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/smoke.png", "assets/images/smoke.png");
			type.set ("assets/images/smoke.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof3-right-cracked.png", "assets/images/roof3-right-cracked.png");
			type.set ("assets/images/roof3-right-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/panel_twitter.png", "assets/images/panel_twitter.png");
			type.set ("assets/images/panel_twitter.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/crane3-filled.png", "assets/images/crane3-filled.png");
			type.set ("assets/images/crane3-filled.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall3-left-cracked.png", "assets/images/wall3-left-cracked.png");
			type.set ("assets/images/wall3-left-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pipe1-right.png", "assets/images/pipe1-right.png");
			type.set ("assets/images/pipe1-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_middle-left.png", "assets/images/billboard_middle-left.png");
			type.set ("assets/images/billboard_middle-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_post.png", "assets/images/billboard_post.png");
			type.set ("assets/images/billboard_post.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/window4_sheet.png", "assets/images/window4_sheet.png");
			type.set ("assets/images/window4_sheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/back.png", "assets/images/back.png");
			type.set ("assets/images/back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof4-right-cracked.png", "assets/images/roof4-right-cracked.png");
			type.set ("assets/images/roof4-right-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/obstacles2.png", "assets/images/obstacles2.png");
			type.set ("assets/images/obstacles2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/window3_sheet.png", "assets/images/window3_sheet.png");
			type.set ("assets/images/window3_sheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall1-middle.png", "assets/images/wall1-middle.png");
			type.set ("assets/images/wall1-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/floor1-right.png", "assets/images/floor1-right.png");
			type.set ("assets/images/floor1-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/button.png", "assets/images/button.png");
			type.set ("assets/images/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof2-right.png", "assets/images/roof2-right.png");
			type.set ("assets/images/roof2-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof1-middle.png", "assets/images/roof1-middle.png");
			type.set ("assets/images/roof1-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/dishes.png", "assets/images/dishes.png");
			type.set ("assets/images/dishes.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/hall1.png", "assets/images/hall1.png");
			type.set ("assets/images/hall1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall2-middle.png", "assets/images/wall2-middle.png");
			type.set ("assets/images/wall2-middle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna3-trimmed.png", "assets/images/antenna3-trimmed.png");
			type.set ("assets/images/antenna3-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_top.png", "assets/images/billboard_top.png");
			type.set ("assets/images/billboard_top.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof1-right.png", "assets/images/roof1-right.png");
			type.set ("assets/images/roof1-right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/background-trimmed.png", "assets/images/background-trimmed.png");
			type.set ("assets/images/background-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/skylight.png", "assets/images/skylight.png");
			type.set ("assets/images/skylight.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof4-middle-cracked.png", "assets/images/roof4-middle-cracked.png");
			type.set ("assets/images/roof4-middle-cracked.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/roof5.png", "assets/images/roof5.png");
			type.set ("assets/images/roof5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pipe2.png", "assets/images/pipe2.png");
			type.set ("assets/images/pipe2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/wall1-left.png", "assets/images/wall1-left.png");
			type.set ("assets/images/wall1-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/gameover.png", "assets/images/gameover.png");
			type.set ("assets/images/gameover.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/antenna6-trimmed.png", "assets/images/antenna6-trimmed.png");
			type.set ("assets/images/antenna6-trimmed.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/billboard_catwalk-left.png", "assets/images/billboard_catwalk-left.png");
			type.set ("assets/images/billboard_catwalk-left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/beep.ogg", "assets/sounds/beep.ogg");
			type.set ("assets/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/flixel.ogg", "assets/sounds/flixel.ogg");
			type.set ("assets/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
